### ISSUE TITLE
setBackgroundColor does not have an effect on the obtained bitmap

### ISSUE THREAD

**Issue by geeeeoffff** [PaNaVTEC/DrawableView#13]
Hi!

I'm using DrawableView, and I set the background color to white.  This does make the background white while I'm drawing, but when I call obtainBitmap I get a black background.  Is this expected?  If so, how can I make the 'real' background white

**Comment by PaNaVTEC** [comment]
I guess you are right, we need to set the background in the obtainBitmap method

**Comment by PaNaVTEC** [comment]
https://github.com/PaNaVTEC/DrawableView/issues/14
