### ISSUE TITLE
Pinch-zoom on view makes drawing disappear

### ISSUE THREAD

**Issue by Odaym** [PaNaVTEC/DrawableView#2]
As the title suggests, when you've drawn some things on the view and then you pinch to zoom, if the Max/Min Zoom levels are set to 0 and 0, the view instantly disappears and you cannot get it back or draw anymore.

If the levels are set to 3.0 and 1.0 as you provided in the example, the view zooms in for a second and then disappears and you cannot get it back or draw anymore.

Also, when beginning to draw, sometimes the draw command doesn't go through and only leaves a little scratch drawn, then you have to press again and also does the same thing. Until you rapidly move your finger and then the thing starts to work fine, but also mid-drawing you can cause it to do that scratch issue again.

Any suggestions? This is just from the first 10 minutes of me trying this library, really great work by the way, much needed and so easy to use!

**Comment by PaNaVTEC** [comment]
Sorry to hear that, I will provide a solution. Thanks for using it :+1:

**Comment by Odaym** [comment]
Ok this is a definite bug that I've just discovered, the issue with the scratch mentioned above is due to trying to draw while dragging your finger horizontally. There is no way to start drawing if you drag your finger horizontally on the view, it *always* cuts off and you have to try again and it will cut off again. Whenever I try to draw while dragging finger vertically or diagonally, works every time.

I've tried this on Nexus 5, glad it wasn't some random bug or something untrackable

**Comment by PaNaVTEC** [comment]
@Odaym Tell me what configuration are you using please, I can't reproduce it. If you set 0 and 0 as min/max on zoom the issue is addressed but is ok, the view is scaling to 0 so if you don't want zoom, you need to setup with 1/1. I will fix later. But what I can't reproduce is setting 1/3 my draw after zoom in/out is still on the screen and I can continue drawing. Please send me the configuration. mine was:

```java 
config.setStrokeColor(getResources().getColor(android.R.color.black));
    config.setStrokeWidth(20.0f);
    config.setMinZoom(1.0f);
    config.setMaxZoom(3.0f);
    config.setCanvasHeight(4000);
    config.setCanvasWidth(4000);
```

I have tried Nexus 7 (last) and Nexus 6. 

Thanks

**Comment by Odaym** [comment]
You are definitely correct about setting Max/Min Zoom levels to be 1 and 1 respectively, this stops any zooming and resolves the problem. Thanks for clearing that up.

Concerning the ability to start drawing by dragging fingers horizontally, this is still a problem and can't draw if starting with a horizontal dragging. My configuration while facing this is the following:

```java
config.setStrokeColor(getResources().getColor(android.R.color.white));
            config.setStrokeWidth(20.0f);
            config.setMinZoom(1.0f);
            config.setMaxZoom(1.0f);
            config.setCanvasWidth(4000);
            config.setCanvasHeight(4000);
```

Now tested on Galaxy S3 also
